create table if not exists service_requests (
    id bigint generated by default as identity primary key,
    object_id bigint references objects(id) on delete cascade,
    title text not null,
    description text,
    priority text not null,
    status text not null,
    created_by text,
    updated_by text,
    updated_at timestamp with time zone,
    created_at timestamp with time zone default now()
);

alter table objects add column if not exists responsible_person text;
alter table service_requests add column if not exists created_by text;
alter table service_requests add column if not exists updated_by text;
alter table service_requests add column if not exists updated_at timestamp with time zone;
alter table reports add column if not exists report_type text default 'Расширенный отчёт';
alter table reports add column if not exists created_by text;
alter table reports add column if not exists storage_path text;

alter table objects disable row level security;
alter table contracts disable row level security;
alter table service_requests disable row level security;
alter table reports disable row level security;

update storage.buckets set public = true where id = 'reports';

drop policy if exists "Allow public delete" on storage.objects;
create policy "Allow public delete"
on storage.objects
for delete
to anon
using (bucket_id = 'reports');
