create table if not exists objects (
    id bigint generated by default as identity primary key,
    name text not null,
    address text not null,
    area numeric not null,
    status text not null,
    created_at timestamp with time zone default now()
);

create table if not exists reports (
    id bigint generated by default as identity primary key,
    file_name text not null,
    file_url text not null,
    created_at timestamp with time zone default now()
);
