create table if not exists objects (
    id bigint generated by default as identity primary key,
    name text not null,
    address text not null,
    area numeric not null,
    status text not null,
    responsible_person text,
    created_at timestamp with time zone default now()
);

create table if not exists contracts (
    id bigint generated by default as identity primary key,
    object_id bigint references objects(id) on delete cascade,
    tenant_name text not null,
    contract_number text not null,
    monthly_payment numeric not null,
    start_date date not null,
    end_date date not null,
    status text not null,
    created_at timestamp with time zone default now()
);

create table if not exists service_requests (
    id bigint generated by default as identity primary key,
    object_id bigint references objects(id) on delete cascade,
    title text not null,
    description text,
    priority text not null,
    status text not null,
    created_at timestamp with time zone default now()
);

create table if not exists reports (
    id bigint generated by default as identity primary key,
    file_name text not null,
    file_url text not null,
    report_type text default 'Расширенный отчёт',
    created_by text,
    created_at timestamp with time zone default now()
);

alter table objects disable row level security;
alter table contracts disable row level security;
alter table service_requests disable row level security;
alter table reports disable row level security;

update storage.buckets
set public = true
where id = 'reports';

drop policy if exists "Allow public uploads" on storage.objects;
drop policy if exists "Allow public read" on storage.objects;

create policy "Allow public uploads"
on storage.objects
for insert
to anon
with check (bucket_id = 'reports');

create policy "Allow public read"
on storage.objects
for select
to anon
using (bucket_id = 'reports');
